#! /usr/bin/env python
from random import shuffle
import sys
l = sys.argv[1:] 
counter = 0
print "sorting list:", str(list)
while not all(l[i] <= l[i+1] for i in xrange(len(l)-1)):
	counter += 1
	shuffle(l)

print "Sorted in ", counter, " steps!"
print l

 